id: IB8A370A0
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:24:13.663604
last_modified: 2023-02-08 15:24:13.663718
source_metadata:
  title: Sarvadharmāpravṛttinirdeśa
  language: sa
bases:
  428E:
    base_file: 428E.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
